config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :posts

  root 'posts#index' 

  get 'category/:name' => 'category#show', as: :category

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_and_belongs_to_many :categories

  def time_format(dbTime)
      time = Time.at(dbTime)
      time.to_formatted_s(:long)
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(title) like ? OR lower(body) like ?", "%#{query.downcase}%", "%#{query.downcase}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(session[:post_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment][:post_id] = session[:post_id]
      params.require(:comment).permit(:body, :post_id, :author)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.order("created_at DESC")
    end 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @postForm = Post.find(params[:id])
    session[:post_id] = @post.id
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all 
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/category/show.html.erb
<div class="banner_show">
<h1>Resolving my Deltas</h1>
</div>
  

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Leave a comment</h3>
  <div class="field form-group">
    <%= f.text_field :author, :placeholder =>  "Name", class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.text_area :body, :placeholder => "Comment", class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resolving my Deltas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'james_icon.png' %>
</head>
<body>
  <div id="wrapper">
<!--     <header>
      <nav class="navbar navbar-default">
        <div class="navbar-header">
          <a href="/" class="navbar-brand"><h1>Delta James</h1></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div>
      </nav>
    </header> -->
    <%= yield %>
  </div>

  <footer>
    <a href="/"><%= image_tag "james_icon.png", id: "footer_icon" %></a>
    <span class="footer_text">
      <a href='/'>James Jalandoni</a><br>
      <a href='https://twitter.com/jamesjalandoni'>twitter</a><br>
      <a href='https://github.com/Eldwick'>github</a>
    </span>
  </footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <ul>
    <% @categories.each do |category| %>
    <li><%= check_box_tag "post[category_ids][]", category.id%> <%= label_tag category.id, category.name %> </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="banner">
<h1>Resolving my Deltas</h1>
</div>

<div class="container">
  <div class="welcome">
    <%= image_tag "james_hi.png", size:"200x205", id: "james_hi", alt: "Edit Entry" %>
    <h2>Hi! Welcome to a collection of my ideas, blabberings, and shower thoughts. </h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In convallis varius dui, a molestie turpis fermentum et. Duis id tristique sem, sed elementum felis. In at turpis tempor, eleifend felis non, venenatis tortor. Nam vel eleifend ligula. </p>
    <p>Nunc felis orci, pulvinar et nulla et, pharetra finibus lectus. Mauris a massa mattis, tristique neque non, pretium diam. Nullam felis felis, venenatis vel augue vitae, elementum bibendum lorem.</p>

  </div>
  <hr>

  <div class="row landing_bottom">
    <div class="col-md-9 landing_posts">
      <% @posts.each do |post| %>
        <h2> <%= post.title %> </h2>
        <p><%= post.body %></p>
        <%= link_to 'See Post', post_path(post) %>
      <% end %>
    </div>
    <div class="col-md-3 landing_aside">
      <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
         <div class="input-append">
           <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Posts" %>
         </div>
      <% end %>
      <h2>Archive</h2>
      <ol>
        <li><a class="href">September</a></li>
        <li><a class="href">October</a></li>
        <li>November</li>
        <li>December</li>
        <li>January</li>
      </ol>
      <h2>Categories</h2>
      <ol>
        <li><a class="href">Rails</a></li>
        <li><a class="href">Node.js</a></li>
        <li>Tech</li>
        <li>Start-ups</li>
        <li>Policy</li>
      </ol>
    </div>
  </div>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="banner_show">
<h1>Resolving my Deltas</h1>
</div>
<div class="container">
  <article>

    <h2>
      <%= @post.title %>
    </h2>
    Posted <%= @post.time_format(@post.created_at)%>
    <div class='post_info'>
      Related to <% @post.categories.each do |category| %>
        <%= link_to category.name, category_path(category.name) %>
      <% end %>
    </div>
    <p>
      <%= @post.body %>
    </p>
  </article>
  <div class="comments">
  <h3>Comments</h3>
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <div class="comment_author"><%= comment.author %></div>
        <p><%= comment.body %></p>
      </div>
    <% end %>
  <%= render "comments/form" %>
  </div>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>